type: rpm-ostree
repos:
install:    
  - python3-pip
  # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
  # other spins. You can remove if you aren't using yafti, but many native
  # apps and binaries require it, so it's a good idea to always include it
  # if you ever download or compile any custom software on your machine.
  - libadwaita
  # small and useful
  - yt-dlp
  - lm_sensors
  - mediainfo
  # for auditing
  - lynis
  - gnome-disk-utility
  - headsetcontrol
  - mpv
  - protonvpn-cli
  - qbittorrent
  - gimp

remove:
  - libvncserver
  - dragon
  - open-vm-tools
  - ibus
  - flatpak
  - virtualbox-guest-additions
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - plasma-browser-integration
  - openssh-server
  - kf5-akonadi-server
  - kde-partitionmanager
  - kwalletmanager5
  - im-chooser
  - cldr-emoji-annotation
  - kemojiselector
  - kmouth
  - kmousetool 
  - kgpg 
  - kmag
  - plasma-welcome
  - kwrite
  - kaddressbook
  - korganizer
  - mediawriter
  - kcalc
  - kfind
  - kcharselect
  - tigervnc-server-minimal
  - kfrb
  - krdc
  - kolourpaint
  - okular
  - kpat
  - plasma-vault
  - cups
  - kmines
  - kpatience
  - dnfdragora
  - mariadb-server
  - konversation
  - kde-connect
  - qt5-qdbusviewer
  - elisa-player
  - kamoso
  - kontact 
  - kmahjongg
  - kmail
  - plasma-discover
  - libreoffice
  





