type: rpm-ostree
repo-files:
  - https://repo.vivaldi.com/stable/vivaldi-fedora.repo
install:    
  - python3-pip
  # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
  # other spins. You can remove if you aren't using yafti, but many native
  # apps and binaries require it, so it's a good idea to always include it
  # if you ever download or compile any custom software on your machine.
  - libadwaita
  # not available as a flatpak, extremely small and useful
  - yt-dlp
  # for auditing
  - lynis
  - lm_sensors
  - mediainfo
  - gnome-disk-utility
  - headsetcontrol
  - vivaldi-stable

# Create these symlinks ../../usr/lib/opt/[name here] in /opt/[name here] to fix installing packages that add files to /opt while building the image
optfix:
  - vivaldi
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
