type: rpm-ostree
repos: 
  - https://copr.fedorainfracloud.org/coprs/qoijjj/hardened_malloc/repo/fedora-39/qoijjj-hardened_malloc-fedora-39.repo
  - https://copr.fedorainfracloud.org/coprs/qoijjj/vscodium/repo/fedora-39/qoijjj-codium-fedora-39.repo
install:    
  - python3-pip
  # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
  # other spins. You can remove if you aren't using yafti, but many native
  # apps and binaries require it, so it's a good idea to always include it
  # if you ever download or compile any custom software on your machine.
  - libadwaita
  # small and useful
  - yt-dlp
  - lm_sensors
  - mediainfo
  # for auditing
  - lynis
  - chkrootkit
  # other packages
  - headsetcontrol
  - mpv
  - qbittorrent
  - gimp
  - hardened_malloc
  - koji
  - codium
  
remove:
  - firefox
  - firefox-langpacks
  - virtualbox-guest-additions
  





