type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/samsepi0l/HardHatOS/repo/fedora-38/samsepi0l-HardHatOS-fedora-38.repo
install:    
  - python3-pip
  # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
  # other spins. You can remove if you aren't using yafti, but many native
  # apps and binaries require it, so it's a good idea to always include it
  # if you ever download or compile any custom software on your machine.
  - libadwaita
  # not available as a flatpak, extremely small and useful
  - yt-dlp
  # for auditing
  - lynis
  - lm_sensors
  - mediainfo
  - gnome-disk-utility
  - headsetcontrol
  - hwloc-devel
  - mpv
  - protonvpn-cli
  - qbittorrent
  - gimp
  - kernel-hardened

remove:
  - kernel
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

