type: rpm-ostree
repos:
  # - https://blah
install:    
remove:
  - kmouth
  - kmousetool 
  - kmag
  - plasma-welcome
  - kwrite
  - korganizer
  - mediawriter
  - kcalc
  - kfind
  - kcharselect
  - tigervnc-server-minimal
  - libvncserver
  - krdc
  - kolourpaint
  - kmines
  - kpatience
  - konversation
  - kde-connect
  - qt5-qdbusviewer
  - kontact 
  - kmail
  - plasma-discover
  - kf5-akonadi-server
  - kde-partitionmanager
  - kwalletmanager5
  - cldr-emoji-annotation
  - okular
  - kpat
  - plasma-vault
  - mariadb-server
  - mariadb-server-utils
  - fedora-chromium-config-kde
  - plasma-browser-integration
  - flatpak
  - fedora-flathub-remote
  - kde-print-manager
  - cups
  - cups-filters
  - braille-printer-app
  - libppd
  - plasma-discover-flatpak
  - ibus
  - ibus-setup
  - ibus-typing-booster
  - open-vm-tools
  - open-vm-tools-desktop
