type: rpm-ostree
repos:
  # - https://blah
install:    
remove:
  - kmousetool 
  - plasma-welcome
  - mediawriter
  - kfind
  - kcharselect
  - kde-connect
  - plasma-discover
  - plasma-discover-notifier
  - kf5-akonadi-server
  - kf5-akonadi-server-mysql
  - kde-partitionmanager
  - kwalletmanager5
  - plasma-vault
  - flatpak
  - fedora-flathub-remote
  - kde-print-manager
  - cups
  - cups-filters
  - braille-printer-app
  - libppd
  - plasma-discover-flatpak
  - ibus
  - ibus-setup
  - ibus-typing-booster
  - open-vm-tools
  - open-vm-tools-desktop
