type: rpm-ostree
repos:
  # - https://blah
install:    
remove:
  - kmousetool 
  - plasma-welcome
  - kfind
  - kcharselect
  - plasma-discover-notifier
  - kf5-akonadi-server
  - kf5-akonadi-server-mysql
  - fedora-flathub-remote
  - toolbox
  - hplip
  - braille-printer-app
  - libppd
  - ibus
  - ibus-panel
  - ibus-m17n
  - ibus-libpinyin
  - ibus-hangul
  - ibus-libzhuyin
  - ibus-qt
  - ibus-anthy
  - ibus-anthy-python
  - ibus-setup
  - ibus-typing-booster
  - open-vm-tools
  - open-vm-tools-desktop
  - krfb
  - krfb-libs
  - qt5-qdbusviewer
