type: rpm-ostree
repos:
  # - https://blah
install:
remove:
  - kde-connect
  - kde-connect-libs
  - kdeconnectd
  - kf5-akonadi-server
  - kf5-akonadi-server-mysql
  - kde-print-manager
  - kde-print-manager-libs
  - open-vm-tools
  - open-vm-tools-desktop
  - qt5-qdbusviewer
