type: rpm-ostree
repos:
  # - https://blah
install:
  - gwenview
remove:
  - kmousetool
  - plasma-welcome
  - kde-connect
  - kde-connect-libs
  - kdeconnectd
  - kf5-akonadi-server
  - kf5-akonadi-server-mysql
  - flatpak
  - flatpak-libs
  - flatpak-selinux
  - flatpak-kcm
  - flatpak-session-helper
  - fedora-flathub-remote
  - toolbox
  - kde-print-manager
  - kde-print-manager-libs
  - hplip
  - libppd
  - plasma-discover-flatpak
  - ibus
  - ibus-panel
  - ibus-m17n
  - ibus-libpinyin
  - ibus-hangul
  - ibus-libzhuyin
  - ibus-qt
  - ibus-anthy
  - ibus-anthy-python
  - ibus-setup
  - ibus-typing-booster
  - open-vm-tools
  - open-vm-tools-desktop
  - krfb
  - krfb-libs
  - qt5-qdbusviewer
