# image will be published to ghcr.io/<user>/<name>
name: kinoite-main-hardened
# description will be included in the image's metadata
description: "Kinoite main with minimal hardening applied"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: common-files.yml

  # common packages last
  - from-file: kinoite-packages.yml
  - from-file: common-packages.yml

  - from-file: common-bling.yml
  - from-file: common-scripts.yml
  
  - type: yafti 