type: rpm-ostree
repos:
  # - https://blah
install:    
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-pop-shell
  - gnome-console
  - gnome-text-editor
  - firewall-config
  - gnome-disk-utility
remove:
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-tour
  - yelp
  - gnome-user-share
  - mod_lua
  - httpd
  - httpd-core
  - mod_http2
  - mod_dnssd
  - gnome-remote-desktop
  - libvncserver
  - hplip
  - cups
  - gutenprint-cups
  - cups-browsed
  - bluez-cups
  - cups-filters
  - braille-printer-app
  - libppd
  - malcontent-ui-libs
  - malcontent-control
  - fedora-flathub-remote
