title: Welcome to secureblue!
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to secureblue!"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.

  can-we-harden-your-kargs:
    source: yafti.screen.consent
    values:
      title: Kernel hardening
      condition:
        run: true
      description: |
        This step will enable additional kernel hardening.
      actions:
        - run: just set-kargs-hardening

  can-we-harden-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Flatpak hardening
      condition:
        run: true
      description: |
        This step will enable hardening for installed flatpaks.
      actions:
        - run: just harden-flatpak

  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Flathub setup
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features. This step will therefore remove all basic Fedora Flatpaks from your system and replace it with Flathub's verified repository. It will also disable the system flatpaks in favor of user flatpaks.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --user --subset=verified flathub-verified https://flathub.org/repo/flathub.flatpakrepo
  
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        Core GNOME Apps:
          description: Core system applications for the GNOME desktop environment.
          default: false
          packages:
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Camera: org.gnome.Snapshot
            - Characters: org.gnome.Characters
            - Clocks: org.gnome.clocks
            - Connections: org.gnome.Connections
            - Contacts: org.gnome.Contacts
            - Disk Usage Analyzer: org.gnome.baobab
            - Document Scanner: org.gnome.SimpleScan
            - Document Viewer: org.gnome.Evince
            - Extension Manager: com.mattjakeman.ExtensionManager
            - Font Viewer: org.gnome.font-viewer
            - Image Viewer: org.gnome.Loupe
            - Logs: org.gnome.Logs
            - Maps: org.gnome.Maps
            - Photos (Organizer): org.gnome.Photos
            - Sushi (Nautilus Previewer): org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Videos (Player): org.gnome.Totem
            - Weather: org.gnome.Weather

        Core KDE Plasma Apps:
          description: Core system applications for the KDE Plasma desktop environment.
          default: false
          packages:
            - Gwenview: org.kde.gwenview
            
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            - Flatseal (Permission Manager): com.github.tchx84.Flatseal

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Website":
            run: /usr/bin/xdg-open https://github.com/secureblue/secureblue
      description: |
        Thanks for trying secureblue, we hope you enjoy it!
