type: script
scripts:
  # hotfix disable authramp
  # - addauthramp.sh
  - optoutauthselect.sh
  - setfilepermissions.sh
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh