name: build-secureblue
on:
  schedule:
    - cron: "00 5 * * *" # build at 5:00 UTC every day 
                          # 80 minutes after the last uBlue images start building
                          # 60 minutes after last wayblue images start building
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build secureblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # non-userns
          # general
          - general/recipe-aurora-main.yml
          - general/recipe-aurora-nvidia.yml
          - general/recipe-aurora-surface.yml
          - general/recipe-aurora-surface-nvidia.yml
          - general/recipe-silverblue-main.yml
          - general/recipe-silverblue-nvidia.yml
          - general/recipe-kinoite-main.yml
          - general/recipe-kinoite-nvidia.yml
          - general/recipe-cinnamon-main.yml
          - general/recipe-cinnamon-nvidia.yml
          - general/recipe-bluefin-main.yml
          - general/recipe-bluefin-nvidia.yml
          - general/recipe-sericea-main.yml
          - general/recipe-sericea-nvidia.yml
          - general/recipe-wayblue-wayfire-main.yml
          - general/recipe-wayblue-wayfire-nvidia.yml
          - general/recipe-wayblue-hyprland-main.yml
          - general/recipe-wayblue-hyprland-nvidia.yml
          - general/recipe-wayblue-river-main.yml
          - general/recipe-wayblue-river-nvidia.yml
          - general/recipe-wayblue-sway-main.yml
          - general/recipe-wayblue-sway-nvidia.yml
          - general/recipe-cosmic-main.yml
          - general/recipe-cosmic-nvidia.yml
          # asus
          - asus/recipe-silverblue-asus.yml
          - asus/recipe-silverblue-asus-nvidia.yml
          - asus/recipe-kinoite-asus.yml
          - asus/recipe-kinoite-asus-nvidia.yml
          - asus/recipe-aurora-asus.yml
          - asus/recipe-aurora-asus-nvidia.yml
          # server
          - server/recipe-server-main.yml
          - server/recipe-server-nvidia.yml
          - server/recipe-server-zfs-main.yml
          - server/recipe-server-zfs-nvidia.yml
          - securecore/recipe-securecore-main.yml
          - securecore/recipe-securecore-nvidia.yml
          - securecore/recipe-securecore-zfs-main.yml
          - securecore/recipe-securecore-zfs-nvidia.yml
          # userns
          # general
          - general/recipe-aurora-surface-userns.yml
          - general/recipe-aurora-surface-nvidia-userns.yml
          - general/recipe-aurora-dx-main-userns.yml
          - general/recipe-aurora-dx-nvidia-userns.yml
          - general/recipe-aurora-dx-surface-nvidia-userns.yml
          - general/recipe-aurora-dx-surface-userns.yml
          - general/recipe-aurora-main-userns.yml
          - general/recipe-aurora-nvidia-userns.yml
          - general/recipe-silverblue-main-userns.yml
          - general/recipe-silverblue-nvidia-userns.yml
          - general/recipe-kinoite-main-userns.yml
          - general/recipe-kinoite-nvidia-userns.yml
          - general/recipe-cinnamon-main-userns.yml
          - general/recipe-cinnamon-nvidia-userns.yml
          - general/recipe-bluefin-main-userns.yml
          - general/recipe-bluefin-nvidia-userns.yml
          - general/recipe-bluefin-dx-main-userns.yml
          - general/recipe-bluefin-dx-nvidia-userns.yml
          - general/recipe-sericea-main-userns.yml
          - general/recipe-sericea-nvidia-userns.yml
          - general/recipe-wayblue-wayfire-main-userns.yml
          - general/recipe-wayblue-wayfire-nvidia-userns.yml
          - general/recipe-wayblue-hyprland-main-userns.yml
          - general/recipe-wayblue-hyprland-nvidia-userns.yml
          - general/recipe-wayblue-river-main-userns.yml
          - general/recipe-wayblue-river-nvidia-userns.yml
          - general/recipe-wayblue-sway-main-userns.yml
          - general/recipe-wayblue-sway-nvidia-userns.yml
          - general/recipe-cosmic-main-userns.yml
          - general/recipe-cosmic-nvidia-userns.yml
          # asus
          - asus/recipe-silverblue-asus-userns.yml
          - asus/recipe-silverblue-asus-nvidia-userns.yml
          - asus/recipe-kinoite-asus-userns.yml
          - asus/recipe-kinoite-asus-nvidia-userns.yml
          - asus/recipe-aurora-asus-userns.yml
          - asus/recipe-aurora-asus-nvidia-userns.yml
          - asus/recipe-aurora-dx-asus-userns.yml
          - asus/recipe-aurora-dx-asus-nvidia-userns.yml
          # server
          - server/recipe-server-main-userns.yml
          - server/recipe-server-nvidia-userns.yml
          - server/recipe-server-zfs-main-userns.yml
          - server/recipe-server-zfs-nvidia-userns.yml
          - securecore/recipe-securecore-main-userns.yml
          - securecore/recipe-securecore-nvidia-userns.yml
          - securecore/recipe-securecore-zfs-main-userns.yml
          - securecore/recipe-securecore-zfs-nvidia-userns.yml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add yq (for reading recipe.yml)
        uses: mikefarah/yq@v4.44.2

      - name: Gather image data from recipe
        run: |
          echo "IMAGE_NAME=$(yq '.name' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_VERSION=$(yq '.image-version' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
          BASE_IMAGE=$(yq '.base-image' ./recipes/${{ matrix.recipe }})
          echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV

      - name: Verify base image
        if: ${{ !contains(env.IMAGE_NAME, 'wayblue') && !contains(env.IMAGE_NAME, 'cinnamon') && !contains(env.IMAGE_NAME, 'securecore') }}
        uses: EyeCantCU/cosign-action/verify@v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}

      - name: Verify base image
        if: ${{ contains(env.IMAGE_NAME, 'wayblue') }}
        uses: EyeCantCU/cosign-action/verify@v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'ghcr.io/wayblueorg'
          pubkey: 'https://raw.githubusercontent.com/wayblueorg/wayblue/live/cosign.pub'

      - name: Verify base image
        if: ${{ contains(env.IMAGE_NAME, 'cinnamon') }}
        uses: EyeCantCU/cosign-action/verify@v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'ghcr.io/legacy-images'
          pubkey: 'https://raw.githubusercontent.com/legacy-images/cinnamon/main/cosign.pub'

      - name: Verify base image
        if: ${{ contains(env.IMAGE_NAME, 'securecore') }}
        uses: EyeCantCU/cosign-action/verify@v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'ghcr.io/secureblue'
          pubkey: 'https://raw.githubusercontent.com/secureblue/coreos/main/cosign.pub'

      - name: Build secureblue
        uses: blue-build/github-action@v1.6.1
        with:          
          cli_version: v0.8.14
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          squash: true
