# image will be published to ghcr.io/<user>/<name>
name: kinoite-asus-hardened
# description will be included in the image's metadata
description: "Kinoite asus with some hardening applied"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-asus
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/common-files.yml
  - from-file: common/kinoite-files.yml
  - from-file: common/kinoite-packages.yml
  - from-file: common/gui-packages.yml
  - from-file: common/common-packages.yml
  - from-file: common/remove-firefox.yml
  - from-file: common/common-scripts.yml
  - type: signing
  - from-file: common/gui-scripts.yml
  - from-file: common/disableuserns-packages.yml
  - from-file: common/disableuserns-scripts.yml
  - type: yafti 